### ISSUE TITLE
Filter Einzelauswahl - \DcGeneral\Events\Table\FilterSetting\DrawSetting' not found

### ISSUE THREAD

**Issue by wilhelmtell9** [MetaModels/filter_select#10]
3.3.7 mit heutigem nightly-tng.zip
Bei erstellen eines filter Einzelauswahl kommt folgender fehler:
https://community.contao.org/de/showthread.php?54630-Filter-Einzelauswahl-DcGeneral-Events-Table-FilterSetting-DrawSetting-not-found
Bei Mehrfachauswahl tritt der fehler auch auf. Bei Textfilter z.B. nicht. Da ist es ok.
Der fehler hat also nur etwas mit der anzeige der filter im BE zu tun, nicht mit den filtern selbst.

**Comment by discordier** [comment]
Sollte sich in der aktuellen Version erledigt haben, die alte Klasse wird nicht mehr referenziert.

**Comment by wilhelmtell9** [comment]
Irgendwie macht das metapalettes nicht mit. Bei Aufruf der install.php kommt u.a.:
Warning: Class 'Bit3\Contao\MetaPalettes\MetaPalettes' not found in system/modules/metapalettes/config/config.php on line 49
Fatal error: Class 'Bit3\Contao\MetaPalettes\MetaPalettes' not found in /home/users.../system/modules/core/library/Contao/System.php on line 122

**Comment by discordier** [comment]
@wilhelmtell9 Das ist ein anderes Ticket.
Das liegt an MetaPalettes und wird hier besprochen: https://github.com/bit3/contao-meta-palettes/issues/32

**Comment by tristanlins** [comment]
Fixed in meta-palettes 1.9.1
