### ISSUE TITLE
[TNG] Leere Optionen werden nicht angezeigt

### ISSUE THREAD

**Issue by cboelter** [MetaModels/filter_select#11]

**Comment by xantippe** [comment]
@cboelter noch aktuell?

**Comment by discordier** [comment]
I do not understand the issue, can someone elaborate and check if it is still valid?

**Comment by zonky2** [comment]
I don´t understand this Issue :-(

**Comment by zonky2** [comment]
at BE is fixed
https://github.com/contao-community-alliance/dc-general/pull/284
