### ISSUE TITLE
[TNG] Anzahl der Elemente im Filter fehlt + verbleibende Tags fehlerhaft

### ISSUE THREAD

**Issue by mj1985** [MetaModels/filter_select#13]
Hallo entweder liegt ein Bedienungsfehler vor oder es wurde grundlegend etwas geändert.
#### Fehler Verbleibende Tags

Ich bekomme die verbleibenen Tags nicht mehr zum arbeiten, obwohl ich es genauso wie bei einer alten Installation eingestellt hab. Es sind alle Updates aus Composer installiert.

Verlinkung zum Thread:
[Thread im Forum](https://community.contao.org/de/showthread.php?56352-Anzahl-der-Elemente-im-Filter-fehlt-weiteres)

Die Übersicht meines Filter: 
![Screenshot Übersicht Filter](http://abload.de/img/bildschirmfoto2015-03ifu0a.png)

Einstellungen in beiden Filtern:
![Screenshot Einstellungen Filter](http://abload.de/img/bildschirmfoto2015-03sruhk.png)
#### Fehler Zählung der Tags

In der früheren Version war es ebenfalls möglich die Tags zu zählen, in der aktuellen ist mir dies auch nicht möglich

**Comment by discordier** [comment]
@zonky2 Betr. des countings hier hatten wir doch ein Sammelticket vom Call?

**Comment by zonky2** [comment]
siehe u.a.
https://github.com/MetaModels/core/issues/312#issuecomment-222599357

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/attribute_select/pull/62
