### ISSUE TITLE
Select-Felder für Tag-Attribute bei Filterdefinition

### ISSUE THREAD

**Issue by danieleicher** [MetaModels/filter_select#3]
Wird bei der Attribut-Definition der Tag-Typ ausgewählt, und soll dieser beim Filter durch ein Select-Feld angezeigt werden, ist dies standardmässig nicht möglich, da eine einfache Auswahl für Tags nicht vorgesehen sind.

Dieser Fall dürfte allerdings öfters vorkommen, deshalb wäre es evtl. sinnvoll, ein spezifisches Filteritem-Template für select-Felder zu erstellen, welches dann ausgewählt werden könnte.

Die entsprechende Community-Diskussion gibt's hier:

https://community.contao.org/de/showthread.php?41002-MetaModels-und-jQuery-Einfachauswahl-f%FCr-Filter-bei-Tags&p=264835#post264835

**Comment by discordier** [comment]
For filtering tag attributes with partial matching, you should use [`filter_tags`](https://github.com/MetaModels/filter_tags) and not `filter_select`

**Comment by discordier** [comment]
@zonky2 can you check this issue please and test if this is still current.

**Comment by zonky2** [comment]
hmm... I'm afraid I don't quite understand the question :-(

If you have a attribute [tags], you can use the filter rule "Single selection" if you wish to work the filter as select - if you use the filter rule "Multi selection", the template "select" is not available

**Comment by zonky2** [comment]
@danieleicher Bitte die Frage nochmal prüfen - ansonsten Ticket schließen!

**Comment by zonky2** [comment]
thx
