### ISSUE TITLE
attribute_translatedselect is not visible in filter_select, but filter_tags

### ISSUE THREAD

**Issue by chameo** [MetaModels/filter_select#4]
I have some Translated tags attributes and a single translated tags attribute. All of them are visible in the select of the filter_tags, but none of them is visible in the filter_select. I have installed Contao 3.2.2 and today's nightly-contao3.

Doesn't it belong in the filter_select? Or did I get it wrong?

**Comment by discordier** [comment]
@chameo could you please check if your issue has been fixed with 5978066d167c991c6bd0dd26f28dbcf9a5e6e792?

It has been in the code for a long time now, sorry to not mention it here before.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@chameo could you please have a final look at this and tell if your issue has been resolved?
