### ISSUE TITLE
Einfache Auswahl mit einem Select Attribute auf ein mehrsprachiges MM 

### ISSUE THREAD

**Issue by tniebergall** [MetaModels/filter_select#9]
Ich habe ein mehrsprachiges MM (MM1) auf welches ich in einem anderen mehrsprachigem MM (MM2) mittels des Select Attributs zugreife.
Lege ich nun in MM2 für das Select Attribut einen Filter vom Typ Einfach Auswahl an bekomme ich im Frontend bei Auswahl des Filters folgende Meldung:

Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM MM1 WHERE alias IN ('value')' at line 1 (SELECT FROM MM1 WHERE alias IN ('value')) thrown in system/modules/core/library/Contao/Database/Statement.php on line 283

**Comment by tniebergall** [comment]
Also der Aufbau ist wie folgt:

In meinem mm_hotels werden dem Hotel mit den Tags Kategorien zugewiesen, diese Tags sind mehrsprachig.

Im Frontend habe ich nun eine Listen-Modul in dem ich den statischen Parameter des Filter auswähle.

Der Filter ist im mm_hotels enthalten und nutzt als Attribut die Tags.

Brauchst du noch mehr Infos? Ich kann dir auch gerne mal einen Testzugang einrichten.

Danke

**Comment by xantippe** [comment]
bei mehrsprachigen MMs inkl. Select-Relation bekomme ich keine Fehlermeldungen

@tniebergall ist das bei Dir noch der Fall?

**Comment by tniebergall** [comment]
Sorry hab aktuell keine Installation mit passender Konfiguration zum testen.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@tniebergall could you please have a final look at this and tell if your issue has been resolved?
